apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: node-todo-cicd-master:latest
      ports:
        - containerPort: 8000
